# Build arguments - all required, no defaults
ARG KERNEL_VERSION
ARG ZFS_VERSION

#####
#
#  Stage 1: Build crun with libkrun TAP support
#
#####
FROM quay.io/fedora/fedora:44 AS crun-builder

ADD https://github.com/containers/crun/archive/refs/tags/1.29.1.tar.gz \
    /tmp/crun-1.29.1.tar.gz
ADD https://github.com/containers/libocispec/archive/872b8b0b7ccb1a121601ede0dcac8c6b8a1008a6.tar.gz \
    /tmp/libocispec-872b8b0b7ccb1a121601ede0dcac8c6b8a1008a6.tar.gz
ADD https://github.com/opencontainers/runtime-spec/archive/d64c1d945da7cf6970061c7c9ff4391fafdf2a15.tar.gz \
    /tmp/runtime-spec-d64c1d945da7cf6970061c7c9ff4391fafdf2a15.tar.gz
ADD https://github.com/opencontainers/image-spec/archive/26647a49f642c7d22a1cd3aa0a48e4650a542269.tar.gz \
    /tmp/image-spec-26647a49f642c7d22a1cd3aa0a48e4650a542269.tar.gz
COPY patches/crun/0001-krun-add-tap-network-annotation.patch /tmp/

RUN dnf install -y --setopt=install_weak_deps=False \
        autoconf automake criu-devel gcc git-core glibc-static gperf \
        json-c-devel libcap-devel libkrun-devel libseccomp-devel libtool \
        make patch protobuf-c-devel python python3-libmount systemd-devel \
        wasmedge-devel zstd

RUN /bin/bash -c 'set -euo pipefail; \
    printf "%s\n" \
      "ac6017a905eb21ba76389ed7327e8f7d6ca55a7c20c69e6c71fb450d4e358c77  /tmp/crun-1.29.1.tar.gz" \
      "9cb0bcd43e25784b44f113045251cf09c291b912c0b862bd505be1a9027c0825  /tmp/libocispec-872b8b0b7ccb1a121601ede0dcac8c6b8a1008a6.tar.gz" \
      "1698ebaa7ff07f8409c084fe9539d0391820e71b7a6e6d877aa1ce8b383a4b50  /tmp/runtime-spec-d64c1d945da7cf6970061c7c9ff4391fafdf2a15.tar.gz" \
      "8668357de6a1162220b2d1fb654a4182a55844b90ad2774c3b99640eec7e2f54  /tmp/image-spec-26647a49f642c7d22a1cd3aa0a48e4650a542269.tar.gz" \
        | sha256sum --check --strict; \
    mkdir /tmp/crun; \
    tar --extract --gzip --file /tmp/crun-1.29.1.tar.gz \
        --directory /tmp/crun --strip-components=1; \
    tar --extract --gzip \
        --file /tmp/libocispec-872b8b0b7ccb1a121601ede0dcac8c6b8a1008a6.tar.gz \
        --directory /tmp/crun/libocispec --strip-components=1; \
    tar --extract --gzip \
        --file /tmp/runtime-spec-d64c1d945da7cf6970061c7c9ff4391fafdf2a15.tar.gz \
        --directory /tmp/crun/libocispec/runtime-spec --strip-components=1; \
    tar --extract --gzip \
        --file /tmp/image-spec-26647a49f642c7d22a1cd3aa0a48e4650a542269.tar.gz \
        --directory /tmp/crun/libocispec/image-spec --strip-components=1; \
    printf "%s\n" "1.29.1" > /tmp/crun/.tarball-version; \
    printf "%s\n" \
      "/* autogenerated.  */" \
      "#ifndef GIT_VERSION" \
      "# define GIT_VERSION \"f0d911de5587342cfeb16473bf32ecdfeaf25957\"" \
      "#endif" \
      > /tmp/crun/.tarball-git-version.h; \
    cd /tmp/crun/libocispec; \
    mkdir -p m4; \
    autoreconf -fi; \
    cd /tmp/crun; \
    patch --batch --forward -p1 \
        < /tmp/0001-krun-add-tap-network-annotation.patch; \
    autoreconf -fi; \
    ./configure --disable-silent-rules --with-libkrun --with-wasmedge \
        --enable-embedded-blake3; \
    make -j "$(nproc)"; \
    install -D -m 0755 crun /out/usr/bin/crun; \
    /out/usr/bin/crun --version | grep -F "crun version 1.29.1"; \
    strings /out/usr/bin/crun | grep -Fx "krun.tap_name"'

#####
#
#  Stage 2: Pull SOPS binary
#
#####
FROM ghcr.io/getsops/sops:v3.13.3@sha256:857f5a151ac0b2bfc55c1e4e5581d66fb8e268e4d106b38e74191f3bac9d58ea AS sops


#####
#
#  Stage 3: Pull Vector runtime
#
#####
FROM docker.io/timberio/vector:0.57.0-distroless-static@sha256:d96454c4e64db59234d9a2b973b02c3b9b09a0674eef685b3955ef7cd03f70a0 AS vector


#####
#
#  Stage 4: Pull Vector license and notice material
#
#####
FROM docker.io/timberio/vector:0.57.0-debian@sha256:ed2134fa8f9844c1ca6405260903c2c2c52f94af9e16bc8fa9de9655134e0b39 AS vector-license


#####
#
#  Stage 5: Pull prebuilt ZFS kmods
#
#####
FROM ghcr.io/samhclark/fedora-zfs-kmods:zfs-${ZFS_VERSION}_kernel-${KERNEL_VERSION} AS zfs-rpms
ARG KERNEL_VERSION
ARG ZFS_VERSION


#####
# 
#  Stage 6: Final image
#
#####
FROM quay.io/fedora/fedora-coreos:stable
ARG KERNEL_VERSION
ARG ZFS_VERSION

# Add container labels for future deduplication
LABEL org.opencontainers.image.title="NAS with ZFS and Tailscale"
LABEL org.opencontainers.image.description="NAS bootc image with prebuilt ZFS kernel modules and Tailscale"
LABEL nas.bootc.zfs-version="${ZFS_VERSION}"
LABEL nas.bootc.kernel-version="${KERNEL_VERSION}"

# Fedora CoreOS points /usr/local into mutable /var by default. This image
# intentionally owns immutable files there, so replace the symlink before
# BuildKit copies the image overlay.
RUN rm /usr/local
COPY overlay-root/ /
COPY --from=sops /usr/local/bin/sops /usr/local/bin/sops
COPY --from=vector /usr/local/bin/vector /usr/local/bin/vector
COPY --from=vector-license /usr/share/vector/NOTICE /usr/share/vector/LICENSE-3rdparty.csv /usr/share/vector/
COPY --from=vector-license /usr/share/vector/licenses /usr/share/vector/licenses

RUN /bin/bash -c 'set -euo pipefail; \
    printf "%s\n" \
      "d /var/lib/prometheus 0755 prometheus prometheus -" \
      "d /var/lib/prometheus/node-exporter 0755 prometheus prometheus -" \
      > /usr/lib/tmpfiles.d/prometheus-node-exporter.conf'

RUN /bin/bash -c 'set -euo pipefail; \
    printf "%s\n" \
      "d /var/lib/nas-secrets 0700 root root -" \
      > /usr/lib/tmpfiles.d/nas-secrets.conf'

RUN --mount=type=bind,from=zfs-rpms,source=/,target=/zfs-rpms \
    /bin/bash -c 'set -euo pipefail; \
    # Copy up the policy store so RPM scriptlets and local policy changes all \
    # transact within this layer. Cross-layer renames can fail with EXDEV and \
    # leave libsemanage unable to replace its non-empty active directory. \
    cp -a /etc/selinux/targeted /etc/selinux/targeted.rebuilt; \
    rm -rf /etc/selinux/targeted; \
    mv /etc/selinux/targeted.rebuilt /etc/selinux/targeted; \
    # Validate that provided kernel version matches the base image kernel \
    [[ "$(rpm -qa kernel --queryformat "%{VERSION}-%{RELEASE}.%{ARCH}")" == "${KERNEL_VERSION}" ]]; \
    arch="$(rpm -qa kernel --queryformat "%{ARCH}")"; \
    dnf install -y \
        crun-krun \
        jq \
        nftables \
        node-exporter \
        smartmontools \
        systemd-networkd \
        tailscale \
        /zfs-rpms/*.noarch.rpm \
        /zfs-rpms/other/zfs-dracut-*.noarch.rpm \
        /zfs-rpms/*."${arch}".rpm; \
    semodule --noreload --install \
        /usr/share/selinux/targeted/nas-krun-tun.cil; \
    mapfile -t image_assets < <( \
        awk "NF && !/^#/" /usr/share/nas/fleet/assets.list \
    ); \
    for asset in "${image_assets[@]}"; do \
        semanage fcontext -a -t container_file_t -r s0 "${asset}(/.*)?"; \
        restorecon -F -R -- "${asset}"; \
    done; \
    mapfile -t shared_storage_paths < <( \
        awk "NF && !/^#/" /usr/share/nas/fleet/shared-storage-paths.list \
    ); \
    for path in "${shared_storage_paths[@]}"; do \
        # The production dataset is not present in the image layer. Install \
        # policy now; the reviewed operator migration applies the labels later. \
        semanage fcontext -a -t container_file_t -r s0 "${path}(/.*)?"; \
    done; \
    depmod -a "$(rpm -qa kernel --queryformat "%{VERSION}-%{RELEASE}.%{ARCH}")"; \
    echo "zfs" > /etc/modules-load.d/zfs.conf; \
    rm -rf /var/lib/pcp /var/cache/dnf; \
    mapfile -t account_units < <( \
        awk "!/^#/" /usr/share/nas/fleet/account-units.list \
    ); \
    mapfile -t storage_units < <( \
        awk "!/^#/" /usr/share/nas/fleet/storage-units.list \
    ); \
    mapfile -t egress_units < <( \
        awk "NF && !/^#/" /usr/share/nas/fleet/egress-units.list \
    ); \
    systemctl enable \
        "${account_units[@]}" \
        "${storage_units[@]}"; \
    if ((${#egress_units[@]})); then \
        systemctl enable "${egress_units[@]}"; \
    fi; \
    systemctl enable \
        bootc-fetch-apply-updates.timer \
        nftables.service \
        nas-krun-network-policy.service \
        systemd-networkd.service \
        tailscaled.service \
        sops-distribute-secrets.service \
        nas-vector.service \
        zfs-scrub-monthly@tank.timer \
        zfs-snapshots-frequently@videos.timer \
        zfs-snapshots-hourly@videos.timer \
        zfs-snapshots-daily@videos.timer \
        zfs-snapshots-weekly@videos.timer \
        disk-health-metrics.timer \
        node_exporter.service; \
    systemctl disable systemd-networkd-wait-online.service; \
    systemctl disable zincati.service; \
    systemctl disable fwupd-refresh.timer; \
    dnf clean all; \
    rm -rf /var/log/dnf*'

COPY --from=crun-builder /out/usr/bin/crun /usr/bin/crun

RUN /bin/bash -c 'set -euo pipefail; \
    /usr/local/bin/vector --version | grep -F "vector 0.57.0"; \
    /usr/local/bin/vector validate \
        --config-yaml /etc/vector/vector.yaml \
        --no-environment --skip-healthchecks; \
    [[ "$(rpm -E "%{fedora}")" == "44" ]]; \
    rpm -q crun >/dev/null; \
    rpm -q crun-krun >/dev/null; \
    [[ "$(readlink /usr/bin/krun)" == "crun" ]]; \
    /usr/bin/crun --version | grep -F "crun version 1.29.1"; \
    grep -aFq "krun.tap_name" /usr/bin/crun; \
    restorecon -F /usr/bin/crun'

RUN ["bootc", "container", "lint"]

LABEL containers.bootc=1
LABEL ostree.bootable=1
ENV container=oci
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
