# ABOUTME: Verifies Vector journald sources are derived from typed Quadlets.

from __future__ import annotations

import re
import unittest
from pathlib import Path
from typing import override

from quadletgen.compiler import compile_fleet
from quadletgen.model import Fleet
from quadletgen.parser import (
    load_fleet_config,
    load_fleet_egress,
    load_fleet_storage,
    load_service,
)
from tests.quadlet_test_support import REPO


class VectorGenerationTests(unittest.TestCase):
    @override
    def setUp(self):
        fleet_file = REPO / "quadlets/_fleet.toml"
        self.fleet = Fleet.build(
            [load_service(path) for path in sorted((REPO / "quadlets").glob("[!_]*.toml"))],
            groups=load_fleet_config(fleet_file),
            resources=load_fleet_storage(fleet_file),
            egress=load_fleet_egress(fleet_file),
        )
        self.artifacts = {
            artifact.path: artifact.content
            for artifact in compile_fleet(self.fleet)
        }
        self.config = self.artifacts[Path("etc/vector/vector.yaml")]

    def test_declared_services_render_quadlet_and_vector_identity(self):
        expected = {
            "alertmanager": 51240,
            "blackbox-exporter": 51230,
            "caddy": 51310,
            "garage": 51110,
            "grafana": 51210,
            "immich-database": 51140,
            "immich-machine-learning": 51160,
            "immich-server": 51130,
            "immich-valkey": 51150,
            "jellyfin": 51120,
            "jellyfin-exporter": 51260,
            "victoria-metrics": 51250,
            "vmalert": 51220,
        }
        expected_components = {
            name.replace("-", "_") for name in expected
        }
        source_components = set(
            re.findall(r"^  ([a-z0-9_]+)_journald:$", self.config, re.MULTILINE)
        )
        transforms_block = self.config.split(
            "transforms:\n", maxsplit=1
        )[1].split("sinks:\n", maxsplit=1)[0]
        transform_components = set(
            re.findall(r"^  ([a-z0-9_]+):$", transforms_block, re.MULTILINE)
        )
        self.assertEqual(source_components, expected_components)
        self.assertEqual(transform_components, expected_components)
        for service_name, uid in expected.items():
            component = service_name.replace("-", "_")
            with self.subTest(service=service_name):
                self.assertIn(
                    "\n".join(
                        (
                            f"  {component}_journald:",
                            "    type: journald",
                            "    include_matches:",
                            "      _UID:",
                            f'        - "{uid}"',
                            "    current_boot_only: false",
                            "    since_now: false",
                        )
                    )
                    + "\n",
                    self.config,
                )
                self.assertIn(
                    "\n".join(
                        (
                            f"  {component}:",
                            "    type: remap",
                            "    inputs:",
                            f"      - {component}_journald",
                            "    source: |",
                            '      .host = "nas"',
                            f'      .service = "{service_name}"',
                        )
                    )
                    + "\n",
                    self.config,
                )
                container_path = Path(
                    f"etc/containers/systemd/users/{uid}/{service_name}.container"
                )
                container = self.artifacts[container_path]
                self.assertIn("LogDriver=journald\n", container)

        sink_inputs = self.config.split(
            "sinks:\n  victoria_logs:\n    type: http\n    inputs:\n",
            maxsplit=1,
        )[1].split("    uri:", maxsplit=1)[0]
        self.assertEqual(
            [line.removeprefix("      - ") for line in sink_inputs.splitlines()],
            sorted(expected_components),
        )

    def test_undeclared_service_is_not_collected(self):
        self.assertNotIn("victoria_logs_journald", self.config)
        self.assertNotIn('      .service = "victoria-logs"\n', self.config)

    def test_vector_config_is_image_managed(self):
        self.assertTrue(
            self.config.startswith(
                "# GENERATED by generate-quadlets.py from quadlets/*.toml"
            )
        )


if __name__ == "__main__":
    unittest.main()
